name: Frontend CI/CD

on:
  push:
    paths:
      - 'front-end/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'front-end/**'

jobs:
  frontend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-end

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint Check (Optional)
        run: |
          if [ -f .eslintrc.js ]; then
            npm run lint
          else
            echo "No linting config found"
          fi

      - name: Build Project
        run: npm run build
